# kindly generated by appropriated Rails generator
Mailjet.configure do |config|
  config.api_key = '05b5666055bbf6dfe42636ff494e1f8e'
  config.secret_key = '7d062374300e5e363c4e1efb32ae61a6'
  config.default_from = 'adilkhansatemirov@yandex.kz'
  # Mailjet API v3.1 is at the moment limited to Send API.
  # We’ve not set the version to it directly since there is no other endpoint in that version.
  # We recommend you create a dedicated instance of the wrapper set with it to send your emails.
  # If you're only using the gem to send emails, then you can safely set it to this version.
  # Otherwise, you can remove the dedicated line into config/initializers/mailjet.rb.
  # config.api_version = 'v3.1'
end
